# This file was generated by GoReleaser. DO NOT EDIT.
cask "usetix" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "546b06fd94cc077bc9de2345261dd974e4675381d626f89e68b91b2aeca833d3"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba93fd4d7163cb408b37109b3945bd8f8fd44495d960cf9df1bd6031290e0c78"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9ece22241a302993ade667157d6ac24a26c79e20994696b5f3865595cb84fd3"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb73faa71accad9566f0cbf4e0ac2cc38caf06616e7b2c3384c9fbb9896c617c"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "usetix"
  desc "Command-line client for the Usetix Admin API"
  homepage "https://www.usetix.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usetix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usetix"]
    end
  end

  # No zap stanza required
end
