# This file was generated by GoReleaser. DO NOT EDIT.
cask "usetix" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "e210eb7242ee63acc4e4dcf9b1294205fd9573f2a45ee630f5d4438e8cbbbd52"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9f36de1129ad0b2b9728f48f567c59c394ecb0d33cde990443b0e9af1dabc72"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d5800e9278eaa7eb1b5aebe99d2080f173c64a8154bd44067f6c59410dba6120"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4470764a6d59da356159657bbbc872f15e9ae94bb656c0d883bf18048642b3d5"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "usetix"
  desc "Command-line client for the Usetix Admin API"
  homepage "https://www.usetix.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usetix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usetix"]
    end
  end

  # No zap stanza required
end
