# This file was generated by GoReleaser. DO NOT EDIT.
cask "usetix" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "3ce6bb80eb2f4f9a280c1b03cb1de38fecd7e9addc0add938855799ec47dc0a0"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ed2dbc8e31d51f4afbcd3c32c7c6948fe6d34034b5e2f0c35a801e3eb827d8b"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3fa1efdd856a101fa035359f5ccd393896d10d5db2334d76e19bb545dff1f7b5"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b3f79cd7c33f1837f977a7b921f785aff889f695ab27cc1bd9e56040b19e160"
      url "https://github.com/gobijan/usetix-cli/releases/download/v#{version}/usetix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "usetix"
  desc "Command-line client for the Usetix Admin API"
  homepage "https://www.usetix.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usetix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usetix"]
    end
  end

  # No zap stanza required
end
